# Generated by Django 4.2.18 on 2025-01-23 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Phong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maPhong', models.CharField(max_length=255)),
                ('tenPhong', models.CharField(max_length=255)),
                ('trangThaiPhong', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Model_ThietBi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maThietBi', models.CharField(max_length=255)),
                ('tenThietBi', models.CharField(max_length=255)),
                ('trangThaiThietBi', models.CharField(max_length=255)),
                ('phongHoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maPhongs', to='Show.model_phong')),
            ],
        ),
    ]
