# Generated by Django 4.2.18 on 2025-01-23 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_phong',
            name='id',
        ),
        migrations.RemoveField(
            model_name='model_thietbi',
            name='id',
        ),
        migrations.AlterField(
            model_name='model_phong',
            name='maPhong',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='model_thietbi',
            name='maThietBi',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
