# Generated by Django 4.2.18 on 2025-01-23 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0002_remove_model_phong_id_remove_model_thietbi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_phong',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_thietbi',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='model_phong',
            name='maPhong',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='model_thietbi',
            name='maThietBi',
            field=models.CharField(max_length=20),
        ),
    ]
