# Generated by Django 4.2.19 on 2025-02-11 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Show', '0003_model_phong_id_model_thietbi_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('face_descriptor', models.TextField()),
                ('attendance_count', models.IntegerField(default=0)),
            ],
        ),
    ]
