echo "version: '3'
services:
  web:
    build: .
    ports:
      - \"8000:8000\"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./staticfiles:/app/staticfiles
    environment:
      - DJANGO_SETTINGS_MODULE=Nhandienkhuonmat.settings
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge" > docker-compose.yml
